title: Oxide
logo: /assets/img/logo.svg
description:
show_downloads: true
google_analytics: G-ZH4VDHJG8M 
theme: jekyll-theme-minimal
github: OfficialOxide
markdown: kramdown
kramdown:
  math_engine: katex
