title: Oxide
logo: /assets/img/logo.svg
description:
show_downloads: true
google_analytics: UA-196349666-1
theme: jekyll-theme-minimal
github: OfficialOxide
markdown: kramdown
url: https://oxyde.ga
kramdown:
  math_engine: katex
